server:
  port: 8082

spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:booking_db}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:booking_user}
    password: ${DB_PASSWORD:booking_pass}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

inventory-service:
  base-url: ${INVENTORY_SERVICE_BASE_URL:http://localhost:8081}

logging:
  level:
    com.bookingsystem: DEBUG
